### PR TITLE
Code Restructuring and many other changes

### PR DESCRIPTION
**Pull request by ralpha**
### Added
- Added `forbid(unsafe_code)` into repo. We don't ever need unsafe code.
- Added additional testing crates: `rrule-debugger` and `rrule-afl-fuzz`.
(only used internally and for debugging)
- Added `examples` folder and moved some code from documentation into examples.
- New and improved error handling consolidated into one object, `RRuleError`.
- Added new method to `RRule` and `RRuleSet`: `all_with_error`, similar to `all` but
returns all dates it could get until it encountered an error.
- Added arbitrary limits for safety reasons.
See ReadMe for more info.
- Improved `rrule` command line tool.
- New `WithError` trait, implemented for `RRuleIter` and `RRuleSetIter`.

### Changed
- License change, from MIT to (MIT or Apache 2.0). (#27)
- Massive code restructuring. Split into `core`, `iter`, `parser` and `validator`.
- Renamed `Frequenzy` to `Frequency`.
- Add limit to `all()`, prevent infinite loops.
- `ParsedOptions` and `Options` are merged together into `RRuleProperties`. (#22)
- `Options` functions changed, for example `byminute` -> `by_minute`.
- `by_easter` is now opt-in with feature flag `by-easter`. (#26)
- `RRule` can only be crated using `new` function with a valid `RRuleProperties`.
- `RRule.option` is no longer public, but can be read by using `get_properties()`.
- `RRuleIter` and `RRuleSetIter` are now part of the public API.
- `NWeekday` has totally changed, but serves the same purpose.
- Updated `chrono-tz` from `0.5.3` to `0.6.0`.

### Removed
- `RRuleSet::new()` replaced with `RRuleSet::default()`.
- `ParsedOptions` and `Options` are now combined as `RRuleProperties`. (#22)
- `NWeekdayIdentifier` replaced with new version of `NWeekday`.
- `by_n_weekday` field removed from `ParsedOptions`, combined into `by_weekday`.
- `concat` and `build` in `Options` are removed, no longer needed.

### Fixed
- Replaced panic on incorrect datetime with error.
- Fix timezone conversions when `TZID` and `Z` is present.
- Stabilized `RRule` parsing from string. Fixed a lot of possible panics.

### Security
- Added security notice to README.md.
- The validation of `RRule` improved the stability of the crate a lot.

This PR also contains a lot of other internal changes.

### CODE REVIEW

**Comment by fmeringdal** [comment]
Amazing work @ralpha 👍 

I will spend today and tomorrow giving it a throughout review. But at first glance, it looks really good.

**Comment by ralpha** [comment]
> Amazing work @ralpha :+1:
> 
> I will spend today and tomorrow giving it a throughout review. But at first glance, it looks really good.

I'm not in a hurry to merge it. So take your time.

I also think that after this is merged we should not directly create a new release as I think documentation, cleanup, and examples could use some improvements. Also I have taken great case in not breaking anything. But with large changes like this, some might have split through the cracks. So I would prefer to see more people test it before a release.

Some tests in `rrule/tests/rfc_tests.rs` that are currently ignored because they do not work. They should be fixed as these are problems I found that already existed in the code.

@omid I'll look at the changes you suggested later today.

**Comment by omid** [comment]
@ralpha Thanks a lot, it LGTM.
I haven't checked the logic, though. I think @fmeringdal will do so.

**Comment by ralpha** [comment]
Resolved merge conflicts and improved the `rrule` CLI tool that was added in last version update.
And added a trait to make code like this nicer to work with.

If everything is okay you can merge the PR. I do think we should hold of with a new version release until some the thing mentioned below are improved.

> I also think that after this is merged we should not directly create a new release as I think documentation, cleanup, and examples could use some improvements. Also I have taken great case in not breaking anything. But with large changes like this, some might have split through the cracks. So I would prefer to see more people test it before a release.

I'll also look into creating some more issues for things that I think could use improvement and bugs I encountered during testing.

I also removed to TODO list from the readme:
- cache (#30)
- more tests around string parsing and validation ( I think this is done in this PR, see: https://github.com/ralpha/rust-rrule/blob/392e739bc110e3a20e3530f1d54a3fa8973a7ecc/rrule/tests/rfc_tests.rs )

**Comment by fmeringdal** [comment]
Thanks again @ralpha ! 🙏 

> I also think that after this is merged we should not directly create a new release

Aha, I missed the *not*. So let us hold off the release for a little longer and do some more testing before possibly releasing it.

Anyways, this is a great PR and a huge step forwards for the project.

**Comment by ralpha** [comment]
> Thanks again @ralpha ! :pray:
> 
> Anyways, this is a great PR and a huge step forwards for the project.

Thanks, 
I hope/think this improves the the crate a lot.
And lets hope we can remove [the warning](https://github.com/fmeringdal/rust-rrule#warning) on top of the readme before we do the next release. :wink:

**Pull request merged**
